# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up pyenv and Python
        uses: "gabrielfalcao/pyenv-action@v14"
        with:
          default: 2.7.18
          versions: 3.8.16
          command: pyenv -v
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Set up Env
        run: |
          sudo apt-get update
          sudo apt-get install -qqy graphicsmagick poppler-utils libreoffice
          sudo gem install docsplit
          pip install -r requirements.txt coverage==5.3.1
      - name: Cache eggs
        uses: actions/cache@v2
        env:
          cache-name: cache-eggs
        with:
          path: ~/buildout-cache/eggs
          key: ${{ runner.os }}-test-${{ env.cache-name }}
          restore-keys: ${{ runner.os }}-test-${{ env.cache-name }}
      - name: buildout
        run: |
          buildout -c ci.cfg annotate
          buildout -c ci.cfg
      - name: test
        run: |
          bin/test -t !robot
  coverage:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up pyenv and Python
        uses: "gabrielfalcao/pyenv-action@v14"
        with:
          default: 2.7.18
          versions: 3.8.16
          command: pyenv -v
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Setup Env
        run: |
          sudo apt-get update
          sudo apt-get install -qqy graphicsmagick poppler-utils libreoffice
          gem install docsplit
          pip install -r requirements.txt coverage==5.3.1
      - name: Cache eggs
        uses: actions/cache@v2
        env:
          cache-name: cache-eggs
        with:
          path: ~/buildout-cache/eggs
          key: ${{ runner.os }}-coverage-${{ env.cache-name }}
          restore-keys: ${{ runner.os }}-coverage-${{ env.cache-name }}
      - name: buildout
        run: |
          buildout -c ci.cfg
      - name: code-analysis
        run: |
          bin/code-analysis
      - name: test coverage
        run: |
          bin/coverage run bin/test -t !robot
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Coveralls
        run: |
          pip3 install -U pip setuptools --no-cache-dir
          pip3 install -U "coveralls>=3.0.0" coverage==5.3.1 --no-cache-dir
      - name: Publish to Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls --service=github
